### PR TITLE
fix(driver): Handle reorg

### LINKED ISSUE #201: Review driver's reorg handling logic
When we running alpha-2, we observed that sometimes the driver didn't handle the reorg correctly (the L2 chain still had the block which was based on the reorged `BlockProposed` event), so the reorg handling logic should have some issues.

### PR DESCRIPTION
**Pull request by cyberhorsey**
We need to handle reorg when an event is removed, previously we were just skipped, but instead we should rewind the chain.

This is very hard to test in the code without generating some mocks and refactoring how our tests work for this, but I think this is at least closer to a solution. Unsure if the spot at where I am handlign the reorg makes sense.

Closes #201  (hopefully ;))

### CODE REVIEW

File: driver/chain_syncer/calldata/syncer.go [hunk 1]
```diff
@@ -223,6 +230,136 @@ func (s *Syncer) onBlockProposed(
 	return nil
 }
 
+// handleReorg detects reorg and rewinds the chain by 1 until we find a block that is still in the chain,
+// then inserts that chain as the new head.
```
Comment (davidtaikocha) [inline driver/chain_syncer/calldata/syncer.go:234]:
```suggestion
// then inserts that block as the new head.
```

File: driver/chain_syncer/calldata/syncer.go [hunk 2]
```diff
@@ -223,6 +230,136 @@ func (s *Syncer) onBlockProposed(
...
+			break
+		}
+
+		block, err = s.rpc.L2.BlockByNumber(ctx, blockId)
+		if err != nil && !errors.Is(err, ethereum.NotFound) {
+			return err
+		}
+
+		if block != nil {
+			// block exists, we can rewind to this block
```
Comment (davidtaikocha) [inline driver/chain_syncer/calldata/syncer.go:262]: do we need to check that this blockID is also smaller than `TaikoL1.state.numBlocks`?

File: driver/chain_syncer/calldata/syncer.go [hunk 3]
```diff
@@ -223,6 +230,136 @@ func (s *Syncer) onBlockProposed(
...
+			lastKnownGoodBlockId = blockId
+			break
+		} else {
+			// otherwise, sub 1 from blockId and try again
+			blockId = new(big.Int).Sub(s.lastInsertedBlockID, big.NewInt(1))
+		}
+	}
+
+	// shouuldnt be able to reach this error because of the 0 check above
```
Comment (davidtaikocha) [inline driver/chain_syncer/calldata/syncer.go:271]:
```suggestion
	// shouldn't be able to reach this error because of the 0 check above
```

File: driver/chain_syncer/calldata/syncer.go [hunk 4]
```diff
@@ -223,6 +230,136 @@ func (s *Syncer) onBlockProposed(
...
+		return fmt.Errorf("error getting l2 parent by block id: %w", err)
+	}
+
+	// reset l1 current to when the last known good block was inserted, and return the event.
+	blockProposedEvent, _, err := s.state.ResetL1Current(ctx, &state.HeightOrID{Height: block.Number()})
+	if err != nil {
+		return fmt.Errorf("faile to reset l1 current: %w", err)
+	}
+
+	tx, err := s.rpc.L1.TransactionInBlock(
```
Comment (davidtaikocha) [inline driver/chain_syncer/calldata/syncer.go:293]: Not sure if this will work if we need to reorg to genesis? (just a corner case..)

File: driver/chain_syncer/calldata/syncer.go [hunk 5]
```diff
@@ -223,6 +230,136 @@ func (s *Syncer) onBlockProposed(
...
+	if lastKnownGoodBlockId == nil {
+		return fmt.Errorf("failed to find last known good block ID after reorg")
+	}
+
+	log.Info(
+		"🔗 Last known good block ID before reorg found",
+		"blockID", event.Id,
+	)
+
+	parent, err := s.rpc.L2ParentByBlockId(ctx, lastKnownGoodBlockId)
```
Comment (davidtaikocha) [inline driver/chain_syncer/calldata/syncer.go:282]: If we need to rewind back to the genesis, we need to use the zero hash instead?

**Review by davidtaikocha — APPROVED** [review]

File: driver/chain_syncer/calldata/syncer.go [hunk 6]
```diff
@@ -25,6 +26,14 @@ import (
 	txListValidator "github.com/taikoxyz/taiko-client/pkg/tx_list_validator"
 )
 
+// ParentBlockInfo is an abstraction between *types.Header and our code, to allow passing in
+// a zero hash and other zero-value fields.
+type ParentBlockInfo struct {
```
Comment (davidtaikocha) [inline driver/chain_syncer/calldata/syncer.go:31]: And seems this abstraction is no more needed?

**Review by davidtaikocha — APPROVED** [review]
